### PR TITLE
Sync p2p code with go-ethereum to fix netrestrict issues in v5 discovery

### LINKED ISSUE #18195: EL P2P: switch from discv4 to discv5
We should refresh our discv5 implementation (feel free to borrow heavily from geth) and switch to it soon (by 31 Jan). See https://notes.ethereum.org/@cskiraly/el-discovery-v5-tracker.

### PR DESCRIPTION
**Pull request by anacrolix**
Fixes #18195.

This started as an attempt to carefully pull fixes for possible issues with netrestrict to discovering the upstream changes are quite significant.

## Packages synced from go-ethereum

The following packages are forked in-tree from `go-ethereum` (synced to v1.16.8):

| Erigon package | go-ethereum package |
|---|---|
| `p2p/` | `p2p/` |
| `p2p/discover/` | `p2p/discover/` |
| `p2p/discover/v4wire/` | `p2p/discover/v4wire/` |
| `p2p/discover/v5wire/` | `p2p/discover/v5wire/` |
| `p2p/dnsdisc/` | `p2p/dnsdisc/` |
| `p2p/enode/` | `p2p/enode/` |
| `p2p/enr/` | `p2p/enr/` |
| `p2p/event/` | `event/` |
| `p2p/netutil/` | `p2p/netutil/` |
| `p2p/rlpx/` | `p2p/rlpx/` |
| `common/mclock/` | `common/mclock/` |
| `common/lru/` | `common/lru/` |

All packages are vendored locally with no `github.com/ethereum/go-ethereum` module dependency.

### CODE REVIEW

File: common/metrics/counter.go [hunk 1]
```diff
@@ -0,0 +1,55 @@
+package metrics
+
+import (
+	"sync/atomic"
+)
+
+// GetOrRegisterCounter returns an existing Counter or constructs and registers
+// a new Counter.
+func GetOrRegisterCounter(name string, r Registry) *Counter {
```
Comment (taratorio) [inline common/metrics/counter.go]: we have our own in
`erigon/diagnostics/metrics`

and definitely dont want to duplicate all of this metrics related code from Geth

(I dont know why it was moved under `diagnostics`, it used to be under `common/metrics`)

File: execution/rlp/decode.go [hunk 2]
```diff
@@ -172,57 +151,71 @@ func (err *decodeError) Error() string {
 }
 
 func wrapStreamError(err error, typ reflect.Type) error {
-	switch {
-	case errors.Is(err, ErrCanonInt):
+	switch err {
+	case ErrCanonInt:
```
Comment (taratorio) [inline execution/rlp/decode.go]: `errors.Is` makes more sense
we dont have to port everything exactly 1:1
we dont usually do that

**Comment by AskAlexSharov** [comment]
run bench and compare with `main`:
```
go test -bench=. -run=Brench -benchmem -count=10 ./execution/rlp > old.txt
go test -bench=. -run=Brench -benchmem -count=10 ./execution/rlp > new.txt
benchstat old.txt new.txt
```

File: go.mod [hunk 3]
```diff
@@ -40,10 +40,11 @@ require (
 	github.com/davecgh/go-spew v1.1.2-0.20180830191138-d8f796af33cc
 	github.com/deckarep/golang-set/v2 v2.8.0
 	github.com/decred/dcrd/dcrec/secp256k1/v4 v4.3.0
-	github.com/dop251/goja v0.0.0-20220405120441-9037c2b61cbf
+	github.com/dop251/goja v0.0.0-20230605162241-28ee0ee714f3
 	github.com/edsrzf/mmap-go v1.2.0
 	github.com/elastic/go-freelru v0.16.0
 	github.com/ethereum/go-bigmodexpfix v0.0.0-20250911101455-f9e208c548ab
+	github.com/ethereum/go-ethereum v1.16.8
```
Comment (AskAlexSharov) [inline go.mod]: forgot remove this line

File: go.mod [hunk 4]
```diff
@@ -99,13 +100,14 @@ require (
 	github.com/quic-go/quic-go v0.49.1
 	github.com/rs/cors v1.11.1
 	github.com/rs/dnscache v0.0.0-20211102005908-e0241e321417
+	github.com/shirou/gopsutil v3.21.11+incompatible
```
Comment (AskAlexSharov) [inline go.mod]: i would advise update `gopsutil` in dedicated PR - because we often reverted it in the past.

File: common/metrics/counter.go (hunk 1 above)
Comment (anacrolix) [reply common/metrics/counter.go]: I kept it in diagnostics/metrics, I think the diff is smaller.

Comment (anacrolix) [reply common/metrics/counter.go]: I moved the execution metrics into execution, which cleaned things up nicely.

File: execution/rlp/decode.go (hunk 2 above)
Comment (anacrolix) [reply execution/rlp/decode.go]: Fixed, cheers

File: go.mod (hunk 3 above)
Comment (anacrolix) [reply go.mod]: I switched common/mclock and common/lru to pull directly from go-ethereum since they are unchanged and to minimize the diff. Is that okay?

File: go.mod (hunk 4 above)
Comment (anacrolix) [reply go.mod]: I think this was kept in because I didn't go mod tidy. I think it's fixed now. There's a v4 imported instead, I assume that doesn't clash.

**Comment by anacrolix** [comment]
> run bench and compare with `main`:
> 
> ```
> go test -bench=. -run=Brench -benchmem -count=10 ./execution/rlp > old.txt
> go test -bench=. -run=Brench -benchmem -count=10 ./execution/rlp > new.txt
> benchstat old.txt new.txt
> ```

```
> benchstat old.txt new.txt
goos: darwin
goarch: arm64
pkg: github.com/erigontech/erigon/execution/rlp
cpu: Apple M4 Max
                             │   old.txt    │               new.txt                │
                             │    sec/op    │    sec/op     vs base                │
Decode-16                      1.933m ± ∞ ¹   1.938m ± ∞ ¹       ~ (p=1.000 n=1) ²
DecodeIntSliceReuse-16         1.964m ± ∞ ¹   1.976m ± ∞ ¹       ~ (p=1.000 n=1) ²
Intsize-16                     1.655n ± ∞ ¹   1.474n ± ∞ ¹       ~ (p=1.000 n=1) ²
Putint-16                      12.41n ± ∞ ¹   12.64n ± ∞ ¹       ~ (p=1.000 n=1) ²
EncodeBigInts-16               3.194µ ± ∞ ¹   3.227µ ± ∞ ¹       ~ (p=1.000 n=1) ²
EncodeConcurrentInterface-16   394.0n ± ∞ ¹   502.8n ± ∞ ¹       ~ (p=1.000 n=1) ²
Hashing/iteratorhashing-16     88.10µ ± ∞ ¹   88.56µ ± ∞ ¹       ~ (p=1.000 n=1) ²
Hashing/fullbodyhashing-16     211.9µ ± ∞ ¹   207.3µ ± ∞ ¹       ~ (p=1.000 n=1) ²
Hashing/fullblockhashing-16    212.9µ ± ∞ ¹   207.9µ ± ∞ ¹       ~ (p=1.000 n=1) ²
geomean                        9.007µ         9.132µ        +1.40%
¹ need >= 6 samples for confidence interval at level 0.95
² need >= 4 samples to detect a difference at alpha level 0.05

                       │    old.txt    │                new.txt                │
                       │      B/s      │      B/s       vs base                │
Decode-16                145.1Mi ± ∞ ¹   144.7Mi ± ∞ ¹       ~ (p=1.000 n=1) ²
DecodeIntSliceReuse-16   162.2Mi ± ∞ ¹   161.2Mi ± ∞ ¹       ~ (p=1.000 n=1) ²
geomean                  153.4Mi         152.8Mi        -0.42%
¹ need >= 6 samples for confidence interval at level 0.95
² need >= 4 samples to detect a difference at alpha level 0.05

                             │    old.txt    │                new.txt                │
                             │     B/op      │     B/op       vs base                │
Decode-16                      2.153Mi ± ∞ ¹   2.153Mi ± ∞ ¹       ~ (p=1.000 n=1) ²
DecodeIntSliceReuse-16         5.451Ki ± ∞ ¹   5.441Ki ± ∞ ¹       ~ (p=1.000 n=1) ²
Intsize-16                       0.000 ± ∞ ¹     0.000 ± ∞ ¹       ~ (p=1.000 n=1) ³
Putint-16                        24.00 ± ∞ ¹     24.00 ± ∞ ¹       ~ (p=1.000 n=1) ³
EncodeBigInts-16                 24.00 ± ∞ ¹     24.00 ± ∞ ¹       ~ (p=1.000 n=1) ³
EncodeConcurrentInterface-16     384.0 ± ∞ ¹     640.0 ± ∞ ¹       ~ (p=1.000 n=1) ²
Hashing/iteratorhashing-16       169.0 ± ∞ ¹     169.0 ± ∞ ¹       ~ (p=1.000 n=1) ³
Hashing/fullbodyhashing-16     150.6Ki ± ∞ ¹   163.5Ki ± ∞ ¹       ~ (p=1.000 n=1) ²
Hashing/fullblockhashing-16    151.4Ki ± ∞ ¹   164.3Ki ± ∞ ¹       ~ (p=1.000 n=1) ²
geomean                                    ⁴                  +7.77%               ⁴
¹ need >= 6 samples for confidence interval at level 0.95
² need >= 4 samples to detect a difference at alpha level 0.05
³ all samples are equal
⁴ summaries must be >0 to compute geomean

                             │   old.txt    │                new.txt                │
                             │  allocs/op   │  allocs/op    vs base                 │
Decode-16                       55.00 ± ∞ ¹    55.00 ± ∞ ¹        ~ (p=1.000 n=1) ²
DecodeIntSliceReuse-16          2.000 ± ∞ ¹    2.000 ± ∞ ¹        ~ (p=1.000 n=1) ²
Intsize-16                      0.000 ± ∞ ¹    0.000 ± ∞ ¹        ~ (p=1.000 n=1) ²
Putint-16                       1.000 ± ∞ ¹    1.000 ± ∞ ¹        ~ (p=1.000 n=1) ²
EncodeBigInts-16                1.000 ± ∞ ¹    1.000 ± ∞ ¹        ~ (p=1.000 n=1) ²
EncodeConcurrentInterface-16    16.00 ± ∞ ¹    32.00 ± ∞ ¹        ~ (p=1.000 n=1) ³
Hashing/iteratorhashing-16      3.000 ± ∞ ¹    3.000 ± ∞ ¹        ~ (p=1.000 n=1) ²
Hashing/fullbodyhashing-16     3.023k ± ∞ ¹   3.825k ± ∞ ¹        ~ (p=1.000 n=1) ³
Hashing/fullblockhashing-16    3.028k ± ∞ ¹   3.832k ± ∞ ¹        ~ (p=1.000 n=1) ³
geomean                                   ⁴                 +13.81%               ⁴
¹ need >= 6 samples for confidence interval at level 0.95
² all samples are equal
³ need >= 4 samples to detect a difference at alpha level 0.05
⁴ summaries must be >0 to compute geomean
```

File: go.mod (hunk 3 above)
Comment (yperbasis) [reply go.mod]: It's better not to introduce a dependency on go-ethereum for consistency's sake (everything is forked from geth, so why `common/mclock` and `common/lru` should be different?)

Comment (taratorio) [reply go.mod]: Yea, I also think we shouldn't have go-ethereum as a dependency (for many reasons). For one, there is a lot of overlap between core types such as `execution/types` so I bet our IDEs will start mixing them up and devs will accidentally be using the wrong auto-imports in files (it will get messy). Another reason is that we are separate from Geth and we have our own different style and identity and architecture. We can use Geth as a reference when we have bugs or are unsure about specs but that's about it. The only components that are sort of similar to Geth at the moment are devp2p and evm (although EVM has diverged in some areas and I imagine it will diverge more). One reason devp2p hasn't diverged much is because we haven't had a dedicated person working on it from our side, but now that's changed so I hope that we can start diverging there too for things that we think we can do better and different.

**Comment by anacrolix** [comment]
Looks like we were stuck on a workflow that was fixed in main. So rebased and should get that. Also fixed a lint that now broke because the lints were improved on main.

File: go.mod (hunk 3 above)
Comment (anacrolix) [reply go.mod]: Ok no worries

Comment (anacrolix) [reply go.mod]: Done.

File: go.mod [hunk 5]
```diff
@@ -105,7 +103,7 @@ require (
 	github.com/spf13/cobra v1.10.1
 	github.com/spf13/pflag v1.0.10
 	github.com/stretchr/testify v1.11.1
-	github.com/supranational/blst v0.3.14
+	github.com/supranational/blst v0.3.16-0.20250831170142-f48500c1fdbe
```
Comment (yperbasis) [inline go.mod]: Please update blst to the officially released v0.3.16

**Review by yperbasis — CHANGES_REQUESTED** [review]

File: execution/rlp/encode.go [hunk 6]
```diff
@@ -68,57 +69,47 @@ type Encoder interface {
...
-		// Encode was called by some type's EncodeRLP.
-		// Avoid copying by writing to the outer encBuffer directly.
-		return outer.encode(val)
-	}
-	eb := encBufferPool.Get().(*encBuffer)
-	defer encBufferPool.Put(eb)
-	eb.reset()
-	if err := eb.encode(val); err != nil {
-		return err
+func Encode(w io.Writer, val interface{}) error {
```
Comment (taratorio) [inline execution/rlp/encode.go:72]: just a general question about the `rlp` changes so I understand this better

what necessitated pulling all of these changes in the rlp package?

is this only the necessary changes needed to get your task done or it has a lot of other stuff just to align the diff?

if this is to just to align the diff with geth, then what about only pulling what's necessary? or are there any optimisations in there that we would want to pull in?

the reason im asking all of this is because afaik people have done optimisations in the rlp package over time (recent example [PR](https://github.com/erigontech/erigon/pull/19122/changes#diff-58433669634df98b790d30ab9a0916e72225e38c26bb7dd876eb127a35a6b82a) ) and we need to carefully review these to make sure those are not lost (our rlp code is a bit of a mess atm)

I see you've run benchmarks [here](https://github.com/erigontech/erigon/pull/18933#issuecomment-3870626371) which is great and they seem to be mostly unchanged apart from a slight bad change in `Hashing/fullblockhashing-16` so maybe this is ok to proceed?

**Review by taratorio — APPROVED** [review]

File: go.mod (hunk 5 above)
Comment (anacrolix) [reply go.mod]: Roger

File: p2p/enode/localnode.go [hunk 7]
```diff
@@ -183,28 +211,28 @@ func (ln *LocalNode) SetFallbackUDP(port int) {
 	ln.mu.Lock()
 	defer ln.mu.Unlock()
 
-	ln.endpoint4.fallbackUDP = port
-	ln.endpoint6.fallbackUDP = port
+	ln.endpoint4.fallbackUDP = uint16(port)
+	ln.endpoint6.fallbackUDP = uint16(port)
 	ln.updateEndpoints()
 }
```
[the remark this answers is not in the document]
Comment (anacrolix) [reply p2p/enode/localnode.go:217]: This matches go-ethereum upstream. All callers pass `realaddr.Port` (from `net.UDPAddr`, which is always in valid range from the OS) or small literal constants like `30303`. The `int` signature exists for API compatibility with `net.UDPAddr.Port`. Adding validation would diverge from upstream for no practical benefit.

File: p2p/netutil/net.go [hunk 8]
```diff
@@ -225,111 +252,88 @@ type DistinctNetSet struct {
...
-		n = value.(uint)
-	}
+	n := s.members[key]
 	if n < s.Limit {
-		s.members.Store(string(key), n+1)
+		s.members[key] = n + 1
 		return true
 	}
 	return false
 }
```
[the remark this answers is not in the document]
Comment (anacrolix) [reply p2p/netutil/net.go:274]: `DistinctNetSet` has always used a plain map in go-ethereum upstream. The `sync.Map` was an Erigon-specific addition. All access goes through `Table.mutex` — every call to `tab.ips.AddAddr`, `tab.ips.RemoveAddr`, `b.ips.AddAddr`, etc. is made while holding that lock. There is no concurrent access to this struct without external synchronization. The plain map is correct and matches upstream.

File: execution/types/receipt.go [hunk 9]
```diff
@@ -310,27 +310,25 @@ func (r *Receipt) DecodeRLP(s *rlp.Stream) error {
...
 		switch r.Type {
 		case AccessListTxType, DynamicFeeTxType, BlobTxType, SetCodeTxType:
-			if err := r.decodePayload(s); err != nil {
+			inner := rlp.NewStream(bytes.NewReader(b[1:]), uint64(len(b)-1))
+			if err := r.decodePayload(inner); err != nil {
 				return err
 			}
 		default:
 			return ErrTxTypeNotSupported
 		}
```
[the remark this answers is not in the document]
Comment (anacrolix) [reply execution/types/receipt.go:331]: Returning `rlp.EOL` here is correct RLP stream protocol. When decoding a list of receipts, an RLP `String` kind with `size == 0` inside a list signals end-of-list. Callers (e.g. list decoders) check for `rlp.EOL` to know when to stop iterating. Changing this to a receipt-specific error would break list decoding. This matches go-ethereum upstream.

File: p2p/discover/common.go [hunk 10]
```diff
@@ -72,34 +91,58 @@ func (cfg Config) withDefaults(defaultReplyTimeout time.Duration) Config {
...
+func (r *reseedingRandom) seed() {
+	var b [8]byte
+	crand.Read(b[:])
+	seed := binary.BigEndian.Uint64(b[:])
+	new := rand.New(rand.NewSource(int64(seed)))
+
+	r.mu.Lock()
+	r.cur = new
+	r.mu.Unlock()
+}
```
[the remark this answers is not in the document]
Comment (anacrolix) [reply p2p/discover/common.go:130]: As of Go 1.20+, `crypto/rand.Read` is documented to never return an error and always fill the buffer completely. It panics internally on failure. The error return value is vestigial. This matches go-ethereum upstream. No change needed.

File: p2p/enr/enr.go [hunk 11]
```diff
@@ -134,7 +153,7 @@ func (r *Record) Load(e Entry) error {
 func (r *Record) Set(e Entry) {
 	blob, err := rlp.EncodeToBytes(e)
 	if err != nil {
-		panic(fmt.Errorf("enr: can't encode %s: %w", e.ENRKey(), err))
+		panic(fmt.Errorf("enr: can't encode %s: %v", e.ENRKey(), err))
```
[the remark this answers is not in the document]
Comment (anacrolix) [reply p2p/enr/enr.go:156]: The error is passed to `panic()`, not returned. `%w` wrapping only matters for `errors.Is`/`errors.As` chains, which do not apply to panics. This also matches go-ethereum upstream which uses `%v` here. Not worth the divergence for no practical effect.

File: execution/rlp/encode.go (hunk 6 above)
Comment (anacrolix) [reply execution/rlp/encode.go:72]: The p2p/enr code strictly needs ~5 new RLP functions: `IntSize`, `BytesSize`, `StringSize` (for `Record.Size()`), and `List()`/`ListEnd()`/`ReadBytes()` (for manual ENR decoding). The receipt.go change also benefits — it replaces the `NewList(size)` hack with a cleaner `ReadBytes()` + fresh stream approach.

Cherry-picking just those functions isn't practical because the Stream internals were redesigned (list tracking, struct layout). You'd end up reimplementing half the refactor anyway.

The rest is go-ethereum alignment: `EncoderBuffer` API, typed uint readers, internal renames, uint256 encoding optimization. These aren't used by p2p but came along with the structural changes.

Benchmarks confirm no meaningful regression. Erigon-specific additions like `DecodeBytesPartial()` are preserved.

Comment (taratorio) [reply execution/rlp/encode.go:72]: sounds good to me 👍

**Review by yperbasis — APPROVED** [review]
