### PR TITLE
rpc: fix txpool_content crash: unknown

### LINKED ISSUE #18076: RPC method txpool_content crashed: unknown
Reported on [Discord](https://discord.com/channels/687972960811745322/738982866670714901/1443556696810324190)

Patrick [beaconcha.in]
since uprading from 3.0.2 to 3.2.2 we see this error in the logs
```
[EROR] [11-27|10:55:32.875] RPC method txpool_content crashed: unknown
[service.go:222 panic.go:792 txpool_grpc_server.go:128 txpool_grpc_server.go:142 pool.go:2727 txpool_grpc_server.go:139 txpool_client.go:57 txpool_api.go:57 value.go:584 value.go:368 service.go:227 handler.go:529 handler.go:479 handler.go:420 handler.go:240 handler.go:333 asm_amd64.s:1700]
```

### PR DESCRIPTION
**Pull request by canepat**
Fixes #18076 

The new `TestQueryAllWithoutPanicUnknown` tests fails i.e. reproduces systematically the issue (100 out of 100 times) with the existing code.

### CODE REVIEW

File: txnprovider/txpool/pool.go [hunk 1]
```diff
@@ -2709,7 +2713,7 @@ func (p *TxPool) deprecatedForEach(_ context.Context, f func(rlp []byte, sender
 	p.lock.Unlock()
 
 	for i := range txns {
-		slotRlp := txns[i].TxnSlot.Rlp
+		slotRlp := rlpValues[i]
 		if slotRlp == nil {
 			v, err := tx.GetOne(kv.PoolTransaction, txns[i].TxnSlot.IDHash[:])
```
Comment (AskAlexSharov) [inline txnprovider/txpool/pool.go:2718]: ok. but then `txns[i].TxnSlot.IDHash` also need move under lock?

Comment (canepat) [reply txnprovider/txpool/pool.go:2718]: apparently, `TxnSlot.IDHash` is written once when `TxnSlots` are parsed in `Fetch` before inserting them into the tx pool and never changed later on, even when they get discarded, so `TxnSlot.IDHash` is immutable
