### PR TITLE
Fix rpc json #4838

### LINKED ISSUE #4784: polygon: trace_block:  insufficient funds for gas * price + value
#### System information

Erigon version: last

OS & Version: Linux
block_num:10852073 10852077
jsonrpc request:{
    "jsonrpc": "2.0",
    "method": "trace_block",
    "params": ["0xa596e9"],  
    "id": 1
}
request result:
{
    "jsonrpc": "2.0",
    "id": 1,
    "error": {
        "code": -32000,
        "message": "first run for txIndex 2 error: insufficient funds for gas * price + value: address 0x1CA971963bdb4BA2BF337c90660674AcFf5Beb3f have 1340837000000000 want 2808193000000000"
    }
}

### LINKED ISSUE #4838: trace rpc stream: return valid json in most of error cases
- as a 1-st step - we can handle it in simple cases: for example handle case when error happening in top-level func (let's say - in `commands/tracing.go:traceBlock`): https://github.com/ledgerwatch/erigon/issues/4637#issuecomment-1176407488
- in-general any error which happen in the middle of trace method (with streaming) will return invalid json now (it will write error in the middle of stream)
- here is some related error:  https://discord.com/channels/687972960811745322/687972960811745326/1001636236307464242
- trace methods docs: https://openethereum.github.io/JSONRPC-trace-module

### PR DESCRIPTION
**Pull request by dafky2000**
A little bit of guesswork and my first foray into Golang... It has fixed the error case I was exhibiting with some trace_filter requests on polygon (same as #4784) and seems to be running well beyond. Should return a trace (or error) for each transaction and not fail mid-way through the batch of transactions.

maybe
fixes #4838 
fixes #4784

### CODE REVIEW

**Comment by AskAlexSharov** [comment]
Unfortunately “ Should return a trace (or error) for each transaction and not fail mid-way through the batch of transactions” is not achievable if do json-streaming. First part of json already sent to client  and can’t undo - when error-in-the-middle happens. Otherwise some traces can eat 60Gb of RAM. https://github.com/ledgerwatch/erigon/issues/4637 Json is not streaming-friendly format. 

Maximum what can do: return “valid json” but not “only error”. See ideas here: https://github.com/ledgerwatch/erigon/issues/4637#issuecomment-1176407488

more on motivation: https://github.com/ledgerwatch/erigon/pull/4647

**Comment by dafky2000** [comment]
Ahhh shucks! I don't think this PR addresses the high memory usage but my intention and the result I'm witnessing is just as you've described - 

> return “valid json” but not “only error”

The machine specs this is currently running on far exceeds 60GB so I may not have noticed.

**Comment by AskAlexSharov** [comment]
Nice. But unfortunately i don’t understand - what changes the PR. Seems it write error to stream - when error happens - in the middle of streamed data. Or i missing something? Maybe you can of me example of request and response?

**Comment by dafky2000** [comment]
The request is:

`curl -X GET -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "method": "trace_filter", "params": [{"fromBlock":"0x1caccda","toBlock":"0x1cacce4","toAddress":["0x9d305a42a3975ee4c1c57555bed5919889dce63f"]}], "id":1}' 'http://localhost:8545/'`

On devel  41f27be1402545779a7a4d01e6bee5c5f265194e the response is invalid JSON - I think due to one failed trace.

```JSON
{
  "jsonrpc":"2.0",
  "id":1,
  "result": [
    null,
    "error": {
      "code":-32000,
      "message":"first run for txIndex 2 error: insufficient funds for gas * price
 + value: address 0x39475f32F1fe9d5B5279400eAcb6ae0a65C5Ae9b have 1791355021271937903 want 1964029590710528768"
    }
}     
```

On fix-rpc-json fa34bce72d65f0db5b68acdd638f15043d7fdc0f I receive 2 traces, the first is an error, the second is a valid trace.

```JSON
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": [
    {
      "error": {
        "code": -32000,
        "message": "first run for txIndex 2 error: insufficient funds for gas * price + value: address 0x39475f32F1fe9d5B5279400eAcb6ae0a65C5Ae9b have 1791355021271937903 want 1964029590710528768"
      }
    },
    {
      "action": {
        "from": "0x7695b9ac52e49f1a8c4c554a072edb225eebfe70",
        "callType": "staticcall",
        "gas": "0x15e26",
        "input": "0x70a08231000000000000000000000000d8bc9881a490b48e4537cae07d6b70ec855bb9c2",
        "to": "0x9d305a42a3975ee4c1c57555bed5919889dce63f",
        "value": "0x0"
      },
      "blockHash": "0x6935ca5b004ad7da60d92e823adbc32e4165623ae62eac7ff7dd2983a4d69a6f",
      "blockNumber": 30067938,
      "result": {
        "gasUsed": "0x266c",
        "output": "0x0000000000000000000000000000000000000000000000000000000000000000"
      },
      "subtraces": 1,
      "traceAddress": [
        3,
        0
      ],
      "transactionHash": "0x29aee314d770d80b3d7ab339510ef983530b72b0e2858a742025f9d186f56b27",
      "transactionPosition": 45,
      "type": "call"
    }
  ]
}
```

**Comment by AskAlexSharov** [comment]
Great. I will try tomorrow

File: rpc/handler.go [hunk 1]
```diff
@@ -477,36 +511,7 @@ func (h *handler) runMethod(ctx context.Context, msg *jsonrpcMessage, callb *cal
...
-			data, derr := json.Marshal(de.ErrorData())
-			if derr == nil {
-				stream.Write(data)
-			} else {
-				stream.WriteString(fmt.Sprintf("%v", derr))
-			}
-		}
-		stream.WriteObjectEnd()
-	}
+	callb.call(ctx, msg.Method, args, stream)
```
Comment (AskAlexSharov) [inline rpc/handler.go:514]: please don't loose error returned by this method. also pass it to HandleError

**Review by AskAlexSharov — CHANGES_REQUESTED** [review]
aha, now I understand how this PR works. 
Only 1 thing need to change - handle lost error.

File: rpc/handler.go (hunk 1 above)
Comment (dafky2000) [reply rpc/handler.go:514]: Shoot! I was on the fence about that one but now realize that's important for the other higher level errors that may occur (before looping through transactions). I'll get this added to the PR asap!

Comment (dafky2000) [reply rpc/handler.go]: That change (and an omission from the rpcdaemon22 port) has been made!

File: rpc/handler.go [hunk 2]
```diff
@@ -479,33 +513,7 @@ func (h *handler) runMethod(ctx context.Context, msg *jsonrpcMessage, callb *cal
...
-			stream.WriteObjectField("data")
-			data, derr := json.Marshal(de.ErrorData())
-			if derr == nil {
-				stream.Write(data)
-			} else {
-				stream.WriteString(fmt.Sprintf("%v", derr))
-			}
-		}
-		stream.WriteObjectEnd()
+		HandleError(err, stream)
```
Comment (AskAlexSharov) [inline rpc/handler.go:516]: Error here was written as top-level object field, not as sub-object.

**Review by AskAlexSharov — CHANGES_REQUESTED** [review]

File: rpc/handler.go (hunk 2 above)
Comment (dafky2000) [reply rpc/handler.go:516]: :hankey: Ok, I've addressed this in 4c640cf5cdb5d0814c72c42bfa0769f438d7df96. It should now set result to null and set the error object in the top-level JSON. Which seems to make the most sense in these cases.

File: rpc/handler.go [hunk 3]
```diff
@@ -479,33 +511,9 @@ func (h *handler) runMethod(ctx context.Context, msg *jsonrpcMessage, callb *cal
...
-			stream.WriteObjectField("data")
-			data, derr := json.Marshal(de.ErrorData())
-			if derr == nil {
-				stream.Write(data)
-			} else {
-				stream.WriteString(fmt.Sprintf("%v", derr))
-			}
-		}
-		stream.WriteObjectEnd()
+		stream.WriteNil();
```
Comment (AskAlexSharov) [inline rpc/handler.go:514]: I think this “nil” makes json invalid. There was no nil and no WriteMore before.

**Review by AskAlexSharov — CHANGES_REQUESTED** [review]

File: rpc/handler.go (hunk 3 above)
Comment (dafky2000) [reply rpc/handler.go:514]: No, because now the nil is setting the result field to "null" which is valid. Then WriteMore inserts the comma before more object fields are added from handle error (error and message). I did take a moment to test the error case where fromBlock > toBlock and the result is valid JSON and what I would expect.

Comment (dafky2000) [reply rpc/handler.go:514]: When any of those errors are returned, the result field is always be uninitialized, so setting it to null or an empty array are the 2 options I saw.

Comment (AskAlexSharov) [reply rpc/handler.go:514]: make sense. then good to go. let me test some other methods

**Review by AskAlexSharov — CHANGES_REQUESTED** [review]
can merge. please fix linter warnings:
make lintci-deps
make lint
```
rpc/handler.go:514: File is not `gofmt`-ed with `-s` (gofmt)
		stream.WriteNil();
		stream.WriteMore();
```

**Comment by dafky2000** [comment]
> can merge. please fix linter warnings: make lintci-deps make lint
> 
> ```
> rpc/handler.go:514: File is not `gofmt`-ed with `-s` (gofmt)
> 		stream.WriteNil();
> 		stream.WriteMore();
> ```

I don't see an option to resolve this comment. Requested another review :-)

**Comment by AskAlexSharov** [comment]
Remove semicolon :-)

**Comment by AskAlexSharov** [comment]
Also error says: use “gofmt”. Just google what is it and enable it in your IDE. Usually we do auto-format code in golang community.

**Comment by dafky2000** [comment]
Yes, my latest commit 52a81841dffa9709194604e02e56a56176f24f23 removes the 2 semicolons.

**Review by AskAlexSharov — APPROVED** [review]

**Comment by AskAlexSharov** [comment]
Thank you. Then i will merge tomorrow

**Comment by AskAlexSharov** [comment]
great work, thank you

**Comment by joucksHua** [comment]
The latest version has been tried and still has this error
branche：devel
Oh, God can take a look！！
{
    "jsonrpc": "2.0",
    "method": "trace_block",
    "params": ["0xa596e9"],
    "id": 1
}
{
    "jsonrpc": "2.0",
    "id": 1,
    "error": {
        "code": -32000,
        "message": "first run for txIndex 2 error: insufficient funds for gas * price + value: address 0x1CA971963bdb4BA2BF337c90660674AcFf5Beb3f have 1340837000000000 want 2808193000000000"
    }
}

**Comment by AskAlexSharov** [comment]
Is it invalid json?

**Comment by joucksHua** [comment]
Through an HTTP request, I want 13 transaction information
```
{
"jsonrpc": "2.0",
"method": "trace_block",
"params": ["0xa596e9"],
"id": 1
}
```
The expectation is the same as here：https://polygonscan.com/txs?block=10852073
But an error is returned
