### PR TITLE
[SharovBot] fix(txpool): downgrade 'txn rlp too big' log to Debug for unwound txns

### LINKED ISSUE #17229: txn rlp too big
#### System information

Erigon version: `./erigon --version`
erigon version 3.1.0-4e297704

OS & Version: Windows/Linux/OSX
Linux 6.16.8/x64

Erigon Command (with flags/config):
```
erigon \
    --datadir=${DATA} \
    --maxpeers=50 \
    --torrent.upload.rate=2mb \
    --torrent.download.rate=25mb \
    --nat=extip:$IP \
    --chain=${CHAIN} \
    --http --ws \
    --http.api=eth,admin,debug,net,trace,web3,erigon,txpool \
    --http.addr=0.0.0.0 --http.port=8545 \
    --http.vhosts=* --http.corsdomain=* \
    --prune.mode=archive
```

Consensus Layer:
caplin

Chain/Network: 
Ethereum/mainnet

#### Expected behaviour
Probably no "txn rlp too big" warnings.

#### Actual behaviour
Between 1 and 10 of these messages per hour in the log:
```
WARN[09-24|09:40:27.625] [txpool.fetch] stream.Recv               err="txn rlp too big"
```

#### Steps to reproduce the behaviour
The node seems to run fine, I just wonder if these warnings are expected behavior.

#### Log

```
INFO[09-24|09:40:19.134] head updated                             hash=0x6462b750d43a845613a7fab9baebb3e161d6cfe3125c4d5194215a94ae74b3ba number=23431464 txnum=3054582129 age=8s execution
=2.438272704s mgas/s=18.47 average mgas/s=26.74 commit=102.196689ms alloc=13.7GB sys=25.7GB
INFO[09-24|09:40:19.479] Timings: Post-Forkchoice (slower than 50ms) Prune Execution=318ms
WARN[09-24|09:40:27.625] [txpool.fetch] stream.Recv               err="txn rlp too big"
INFO[09-24|09:40:27.629] head updated                             hash=0x4e9b7652528b8dcefb3b57ccbfae3d6266db58b6db3fdaf9eb9c486ed062c614 number=23431465 txnum=3054582329 age=4s execution
=859.50331ms mgas/s=33.43 average mgas/s=26.79 commit=87.881554ms alloc=14.0GB sys=25.7GB
INFO[09-24|09:40:27.870] Timings: Post-Forkchoice (slower than 50ms) Prune Execution=215ms
INFO[09-24|09:40:40.132] head updated
```

### PR DESCRIPTION
**Pull request by Giulio2002**
Clean version of #19315 — removes unrelated Caplin commits from the branch history.

## Changes

- **FORWARD (new) txns**: added `txnType` to existing Debug log for better diagnostics
- **UNWIND txns**: downgrade `ErrRlpTooBig` errors from Debug to Debug (was previously same level but now explicitly separated), keep `Warn` for unexpected errors
- Added `txnType` to both log paths for better diagnostics

When valid on-chain transactions exceed the txpool's RLP size limit during unwind processing, this is expected behavior (the txn was valid enough to be included in a block). Logging at Warn level creates noise in production logs.

Fixes #17229
Supersedes #19315

### CODE REVIEW

**Comment by Giulio2002** [comment]
**[SharovBot]** 🔄 Restarted failing CI workflows: 22188851998 (Kurtosis Assertoor), 22188851987 (Unit tests Windows), 22188852021 (All tests)

**Review by taratorio — APPROVED** [review]

File: txnprovider/txpool/fetch.go [hunk 1]
```diff
@@ -560,7 +560,8 @@ func (f *Fetch) handleStateChangesRequest(ctx context.Context, req *remoteproto.
 					minedTxns.Append(utx, sender, false)
 					return nil
 				}); err != nil && !errors.Is(err, context.Canceled) {
-					f.logger.Debug("[txpool.fetch] stream.Recv", "dir", change.Direction, "index", i, "err", err)
+					txnType, _ := PeekTransactionType(change.Txs[i])
+					f.logger.Debug("[txpool.fetch] stream.Recv", "dir", "new", "txnType", txnType, "index", i, "err", err)
```
Comment (taratorio) [inline txnprovider/txpool/fetch.go]: keep `"dir", change.Direction` unchanged

File: txnprovider/txpool/fetch.go [hunk 2]
```diff
@@ -581,7 +582,12 @@ func (f *Fetch) handleStateChangesRequest(ctx context.Context, req *remoteproto.
 					}
 					return nil
 				}); err != nil && !errors.Is(err, context.Canceled) {
-					f.logger.Debug("[txpool.fetch] stream.Recv", "dir", change.Direction, "index", i, "err", err)
+					txnType, _ := PeekTransactionType(change.Txs[i])
+					if errors.Is(err, ErrRlpTooBig) {
+						f.logger.Debug("[txpool.fetch] stream.Recv", "dir", "unwound", "txnType", txnType, "index", i, "err", err)
```
Comment (taratorio) [inline txnprovider/txpool/fetch.go]: keep `"dir", change.Direction` unchanged

File: txnprovider/txpool/fetch.go [hunk 3]
```diff
@@ -581,7 +582,12 @@ func (f *Fetch) handleStateChangesRequest(ctx context.Context, req *remoteproto.
...
+					} else {
+						f.logger.Warn("[txpool.fetch] stream.Recv", "dir", "unwound", "txnType", txnType, "index", i, "err", err)
```
Comment (taratorio) [inline txnprovider/txpool/fetch.go]: keep `"dir", change.Direction` unchanged

File: txnprovider/txpool/fetch.go (hunk 1 above)
Comment (Giulio2002) [reply txnprovider/txpool/fetch.go]: **[SharovBot]** Fixed — reverted to `change.Direction` in all three log calls. Commit: 1b1f2a7

File: txnprovider/txpool/fetch.go (hunk 2 above)
Comment (Giulio2002) [reply txnprovider/txpool/fetch.go]: **[SharovBot]** Fixed — reverted to `change.Direction` in all three log calls. Commit: 1b1f2a7

File: txnprovider/txpool/fetch.go (hunk 3 above)
Comment (Giulio2002) [reply txnprovider/txpool/fetch.go]: **[SharovBot]** Fixed — reverted to `change.Direction` in all three log calls. Commit: 1b1f2a7

File: txnprovider/txpool/fetch.go [hunk 4]
```diff
@@ -581,7 +582,12 @@ func (f *Fetch) handleStateChangesRequest(ctx context.Context, req *remoteproto.
 					}
 					return nil
 				}); err != nil && !errors.Is(err, context.Canceled) {
-					f.logger.Debug("[txpool.fetch] stream.Recv", "dir", change.Direction, "index", i, "err", err)
+					txnType, _ := PeekTransactionType(change.Txs[i])
+					if errors.Is(err, ErrRlpTooBig) {
```
Comment (taratorio) [inline txnprovider/txpool/fetch.go]: remove this if statement and stick to just having 1 logger.Debug line as before, but keep the new addition of txnType

Comment (Giulio2002) [reply txnprovider/txpool/fetch.go]: **[SharovBot]** Fixed — removed the `if ErrRlpTooBig` branch entirely, now a single `logger.Debug` line with `txnType` added. Commit: 2283021

**Review by taratorio — APPROVED** [review]
